apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.image.name }}-deploy"
  labels:
    deploy: {{ .Values.image.label }}
spec:
  progressDeadlineSeconds: 60
  replicas: {{ .Values.replicaCount }}
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.rollingUpdate.maxUnavailablePercentage}}
      maxSurge: {{ .Values.rollingUpdate.maxSurgePercentage}}
    type: RollingUpdate  
  selector:
    matchLabels:
      app: {{ .Values.image.label }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.label }}
    spec:
      containers:
      - image: "{{ .Values.repository.image }}:{{ .Values.repository.tag }}"
        imagePullPolicy: {{ .Values.repository.pullPolicy }}
        imagePullSecrets:
          - name: regcred
        name: {{ .Values.image.name }}
        ports:
          - containerPort: {{ .Values.image.containerPort }}
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP        
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 1
        readinessProbe:
          httpGet:
            path: /api/healthcheck/poi
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 1
        env:
          - name: WEB_SERVER_BASE_URI
            value: 'http://0.0.0.0'
          - name: WEB_PORT
            value: '8080'
          - name: ASPNETCORE_ENVIRONMENT
            value: 'Production'